# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mavUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1404, 800)
        Form.setMouseTracking(False)
        Form.setAcceptDrops(True)
        Form.setToolTipDuration(-1)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.battery = QtWidgets.QWidget(Form)
        self.battery.setGeometry(QtCore.QRect(1110, 0, 191, 111))
        self.battery.setObjectName("battery")
        self.batteryImage = QtWidgets.QLabel(self.battery)
        self.batteryImage.setGeometry(QtCore.QRect(0, 0, 211, 121))
        self.batteryImage.setAutoFillBackground(False)
        self.batteryImage.setStyleSheet("")
        self.batteryImage.setObjectName("batteryImage")
        self.batteryProgressBar = QtWidgets.QProgressBar(self.battery)
        self.batteryProgressBar.setGeometry(QtCore.QRect(8, 15, 161, 88))
        self.batteryProgressBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.batteryProgressBar.setStyleSheet("")
        self.batteryProgressBar.setProperty("value", 24)
        self.batteryProgressBar.setTextVisible(False)
        self.batteryProgressBar.setObjectName("batteryProgressBar")
        self.batteryProgressBar.raise_()
        self.batteryImage.raise_()
        self.radar = QtWidgets.QWidget(Form)
        self.radar.setGeometry(QtCore.QRect(1000, 400, 400, 400))
        self.radar.setObjectName("radar")
        self.radarImage = QtWidgets.QLabel(self.radar)
        self.radarImage.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.radarImage.setStyleSheet("")
        self.radarImage.setObjectName("radarImage")
        self.enemy = QtWidgets.QLabel(self.radar)
        self.enemy.setGeometry(QtCore.QRect(120, 110, 16, 16))
        self.enemy.setStyleSheet("")
        self.enemy.setObjectName("enemy")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyQt5 Window"))
        self.batteryImage.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/images/battery400x100.png\"/></p></body></html>"))
        self.radarImage.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/images/radar400x400.png\"/></p></body></html>"))
        self.enemy.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/images/enemy10x10.png\"/></p></body></html>"))
import qrc_rc
