# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(615, 476)


        self.label = QtWidgets.QLabel(Form)
        self.pixmap = QPixmap("pointer.png")
        self.label.setPixmap(self.pixmap)

        self.label.setGeometry(QtCore.QRect(260, 70, 81, 271))
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0,0,80,20))
        self.label.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        #self.label.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/pointer.png\"/></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Click Me"))

import speedometer_rc
